### ISSUE TITLE
Update assertj dependency to 1.7.1

### ISSUE THREAD

**Issue by MichaelEvans** [square/assertj-android#163]
Looks like there are binary incompatible changes when upgrading from 1.7.0 to 1.7.1. 

```
java.lang.NoSuchMethodError: org.assertj.core.api.Assertions.assertThat(I)Lorg/assertj/core/api/IntegerAssert;
	at org.assertj.android.api.view.AbstractViewAssert.isGone(AbstractViewAssert.java:773)
...
```

**Comment by JakeWharton** [comment]
Thanks, Obama.

**Comment by JakeWharton** [comment]
01d9ec10d97800af6a00bbd847bca60d1caa4d61
